export const environment = {
  production: true,
  url_user: 'https://www.sanratsolutions.com/prd/usuarios/public/users',
  url_module: 'https://www.sanratsolutions.com/prd/usuarios/public/modules',
  url_component: 'https://www.sanratsolutions.com/prd/usuarios/public/components',
  url_rol: 'https://www.sanratsolutions.com/prd/usuarios/public/rols',
  url_rol_option: 'https://www.sanratsolutions.com/prd/usuarios/public/rols_options',
  url_option: 'https://www.sanratsolutions.com/prd/usuarios/public/options',
  url_category: 'https://www.sanratsolutions.com/prd/usuarios/public/categories',
  url_parameter: 'https://www.sanratsolutions.com/prd/usuarios/public/parameters',
  url_storage: 'https://www.sanratsolutions.com/prd/usuarios/storage/app/public/',
  url_ventas_storage: 'https://www.sanratsolutions.com/prd/ventas/storage/app/public/',
  url_type_service: 'https://www.sanratsolutions.com/prd/usuarios/public/type_service',

  url_authentication: 'https://www.sanratsolutions.com/prd/ventas/public/authentication',
  url_person: 'https://www.sanratsolutions.com/prd/ventas/public/persons',
  url_enterprise: 'https://www.sanratsolutions.com/prd/ventas/public/enterprises',
  url_operation: 'https://www.sanratsolutions.com/prd/ventas/public/operations',
  url_products: 'https://www.sanratsolutions.com/prd/ventas/public/products',
  url_payment: 'https://www.sanratsolutions.com/prd/ventas/public/payments',
  url_expenses: 'https://www.sanratsolutions.com/prd/ventas/public/expenses',
  url_note: 'https://www.sanratsolutions.com/prd/ventas/public/notes',
  url_position: 'http://localhost/ventasV0/public/positions',
  
  /*
  url_user: 'http://localhost/usuariosV1/public/users',
  url_module: 'http://localhost/usuariosV1/public/modules',
  url_component: 'http://localhost/usuariosV1/public/components',
  url_rol: 'http://localhost/usuariosV1/public/rols',
  url_rol_option: 'http://localhost/usuariosV1/public/rols_options',
  url_option: 'http://localhost/usuariosV1/public/options',
  url_category: 'http://localhost/usuariosV1/public/categories',
  url_parameter: 'http://localhost/usuariosV1/public/parameters',
  url_storage: 'http://localhost/usuariosV1/storage/app/public/',
  url_ventas_storage: 'http://localhost/ventasV1/storage/app/public/',

  url_authentication: 'http://localhost/ventasV1/public/authentication',
  url_person: 'http://localhost/ventasV1/public/persons',
  url_enterprise: 'http://localhost/ventasV1/public/enterprises',
  url_operation: 'http://localhost/ventasV1/public/operations',
  url_products: 'http://localhost/ventasV1/public/products',
  url_payment: 'http://localhost/ventasV1/public/payments',
  url_expenses: 'http://localhost/ventasV1/public/expenses',
  url_note: 'http://localhost/ventasV1/public/notes',
  */

  clearMessageDelayMs: 5000,
  refreshInterval: 1000,
  min_products: 20,
  medium_products: 50,
  days_sold: 7,
  consolidate_day: 2,

  type_operation_purchase: 'PURCHASE',
  type_operation_sale: 'SALE',

  state_user: 'STATE_USER',
  type_payment: 'PAYMENT_TYPE',
  type_enterprise: 'TYPE_ENTERPRISE',
  discounts_purchase: 'DISCOUNTS_PURCHASE',
  type_ids: 'TYPE_ID',
  efecty_payment: 'Efectivo',
  credit_payment: 'Crédito',
  category_product: 'CATEGORY_PRODUCT',
  presentation_product: 'PRODUCT_PRESENTATION',
  clothes: 'VESTUARIO',
  medicines: 'MEDICAMENTO',
  foods: 'ALIMENTO',
  package: 'PAQUETE',
  individual: 'INDIVIDUAL',
  tax_purchase: 'TAX_PURCHASE',
  positions_person: 'POSITION_PERSON',
  enterprise_owner: 'OWNER',
  enterprise_provider: 'PROVIDER',
  laboral_state: 'LABORAL_STATE',
  product_type: 'PRODUCT_TYPE',
  type_expense: 'TYPE_EXPENSE',
  rol_client: 'Cliente',
  rol_employee: 'Employee',
  state_rol_person_active: 'Activo',
  salary_type: 'SALARY_TYPE',

  state_initial_purchase: 'CREADA',
  state_payment_purchase: 'PAGADA',
  state_opened_purchase: 'ABIERTA',

  sales: 'SALE',
  purchase: 'PURCHASE',

  type_product_purchase: 'COMPRA_PROVEEDORES',
  mode_service: 'MODE_SERVICE',
  type_service: 'TYPE_SERVICE',
  size_enterprise: 'SIZE_ENTERPRISE',
};
